In [6]:
from pathlib import Path
import pandas as pd

In [7]:
DATA_PATH = Path(
    "data/raw/Supermart Grocery Sales - Retail Analytics Dataset.csv"
)

In [8]:
if not DATA_PATH.exists():
    raise FileNotFoundError(f"Dataset not found: {DATA_PATH}")

In [9]:
df = pd.read_csv(DATA_PATH)

In [10]:
print("\n--- DATASET SHAPE ---")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

--- DATASET SHAPE ---
Rows: 9994
Columns: 11

In [11]:
print("\n--- COLUMN NAMES ---")
print(df.columns.tolist())

--- COLUMN NAMES ---
['Order ID', 'Customer Name', 'Category', 'Sub Category', 'City', 'Order Date', 'Region', 'Sales', 'Discount', 'Profit', 'State']

In [12]:
print("\n--- FIRST 5 ROWS ---")
print(df.head().to_string(index=False))

--- FIRST 5 ROWS ---
Order ID Customer Name         Category     Sub Category        City Order Date Region  Sales  Discount  Profit      State
     OD1        Harish     Oil & Masala          Masalas     Vellore 11-08-2017  North   1254      0.12  401.28 Tamil Nadu
     OD2         Sudha        Beverages    Health Drinks Krishnagiri 11-08-2017  South    749      0.18  149.80 Tamil Nadu
     OD3       Hussain      Food Grains     Atta & Flour  Perambalur 06-12-2017   West   2360      0.21  165.20 Tamil Nadu
     OD4       Jackson Fruits & Veggies Fresh Vegetables  Dharmapuri 10-11-2016  South    896      0.25   89.60 Tamil Nadu
     OD5       Ridhesh      Food Grains  Organic Staples        Ooty 10-11-2016  South   2355      0.26  918.45 Tamil Nadu

In [13]:
print("\n--- DATA TYPES ---")
print(df.dtypes.to_string())

--- DATA TYPES ---
Order ID          object
Customer Name     object
Category          object
Sub Category      object
City              object
Order Date        object
Region            object
Sales              int64
Discount         float64
Profit           float64
State             object

In [14]:
print("\n--- MISSING VALUES ---")
print(df.isnull().sum().to_string())

--- MISSING VALUES ---
Order ID         0
Customer Name    0
Category         0
Sub Category     0
City             0
Order Date       0
Region           0
Sales            0
Discount         0
Profit           0
State            0

In [15]:
print("\n--- DUPLICATE ROWS ---")
print(df.duplicated().sum())

--- DUPLICATE ROWS ---
0

In [16]:
print("\n--- NUMERICAL SUMMARY ---")
print(df.describe().to_string())

--- NUMERICAL SUMMARY ---
             Sales     Discount       Profit
count  9994.000000  9994.000000  9994.000000
mean   1496.596158     0.226817   374.937082
std     577.559036     0.074636   239.932881
min     500.000000     0.100000    25.250000
25%    1000.000000     0.160000   180.022500
50%    1498.000000     0.230000   320.780000
75%    1994.750000     0.290000   525.627500
max    2500.000000     0.350000  1120.950000

In [19]:

print("=== DATE RANGE ===")
print("Start date:", df["Order Date"].min())
print("End date:", df["Order Date"].max())

print("\n=== UNIQUE BUSINESS DIMENSIONS ===")
for col in ["Category", "Sub Category", "City", "Region", "State"]:
    if col in df.columns:
        print(f"{col}: {df[col].nunique()} unique values")

print("\n=== SALES AND PROFIT ===")
for col in ["Sales", "Profit", "Discount", "Quantity"]:
    if col in df.columns:
        print(f"\n{col}")
        print(df[col].describe())

=== DATE RANGE ===
Start date: 01-01-2018
End date: 9/30/2018

=== UNIQUE BUSINESS DIMENSIONS ===
Category: 7 unique values
Sub Category: 23 unique values
City: 24 unique values
Region: 5 unique values
State: 1 unique values

=== SALES AND PROFIT ===

Sales
count    9994.000000
mean     1496.596158
std       577.559036
min       500.000000
25%      1000.000000
50%      1498.000000
75%      1994.750000
max      2500.000000
Name: Sales, dtype: float64

Profit
count    9994.000000
mean      374.937082
std       239.932881
min        25.250000
25%       180.022500
50%       320.780000
75%       525.627500
max      1120.950000
Name: Profit, dtype: float64

Discount
count    9994.000000
mean        0.226817
std         0.074636
min         0.100000
25%         0.160000
50%         0.230000
75%         0.290000
max         0.350000
Name: Discount, dtype: float64

In [21]:
print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub Category', 'City', 'Order Date', 'Region', 'Sales', 'Discount', 'Profit', 'State']

In [22]:
for col in df.columns:
    print(repr(col))

'Order ID'
'Customer Name'
'Category'
'Sub Category'
'City'
'Order Date'
'Region'
'Sales'
'Discount'
'Profit'
'State'

In [23]:
# Normalize accidental spaces in column names
df.columns = df.columns.str.strip()

print("Available columns:", df.columns.tolist())

if "Order Date" in df.columns:
    df["Order Date"] = pd.to_datetime(
        df["Order Date"], errors="coerce"
    )
    print("Invalid order dates:", df["Order Date"].isna().sum())

if "Ship Date" in df.columns:
    df["Ship Date"] = pd.to_datetime(
        df["Ship Date"], errors="coerce"
    )
    print("Invalid shipping dates:", df["Ship Date"].isna().sum())
else:
    print("Ship Date column not available; shipping-date check skipped.")

Available columns: ['Order ID', 'Customer Name', 'Category', 'Sub Category', 'City', 'Order Date', 'Region', 'Sales', 'Discount', 'Profit', 'State']
Invalid order dates: 5952
Ship Date column not available; shipping-date check skipped.

In [24]:

# Retail dataset: business data quality audit

print("Dataset shape:", df.shape)

# 1. Missing values
print("\n=== MISSING VALUES ===")
display(df.isna().sum().to_frame("missing_count"))

# 2. Duplicate records
print("\n=== DUPLICATES ===")
print("Exact duplicate rows:", df.duplicated().sum())
print("Duplicate Order IDs:", df["Order ID"].duplicated().sum())

# 3. Date validation
print("\n=== DATE VALIDATION ===")
df["Order Date"] = pd.to_datetime(
    df["Order Date"], errors="coerce"
)
print("Invalid dates:", df["Order Date"].isna().sum())

# 4. Numeric business checks
print("\n=== BUSINESS VALUE CHECKS ===")
print("Sales <= 0:", (df["Sales"] <= 0).sum())
print("Negative discounts:", (df["Discount"] < 0).sum())
print("Discounts above 1:", (df["Discount"] > 1).sum())
print("Negative profit:", (df["Profit"] < 0).sum())

# 5. Category consistency
print("\n=== BUSINESS DIMENSIONS ===")
for col in ["Category", "Sub Category", "City", "Region", "State"]:
    print(f"{col}: {df[col].nunique()} unique values")

# 6. Date coverage
print("\n=== DATE COVERAGE ===")
print("Start:", df["Order Date"].min())
print("End:", df["Order Date"].max())

Dataset shape: (9994, 11)

=== MISSING VALUES ===

               missing_count
Order ID                   0
Customer Name              0
Category                   0
Sub Category               0
City                       0
Order Date              5952
Region                     0
Sales                      0
Discount                   0
Profit                     0
State                      0

=== DUPLICATES ===
Exact duplicate rows: 0
Duplicate Order IDs: 0

=== DATE VALIDATION ===
Invalid dates: 5952

=== BUSINESS VALUE CHECKS ===
Sales <= 0: 0
Negative discounts: 0
Discounts above 1: 0
Negative profit: 0

=== BUSINESS DIMENSIONS ===
Category: 7 unique values
Sub Category: 23 unique values
City: 24 unique values
Region: 5 unique values
State: 1 unique values

=== DATE COVERAGE ===
Start: 2015-01-03 00:00:00
End: 2018-12-11 00:00:00

In [25]:

# Reload original CSV so we can inspect untouched date values
from pathlib import Path
import pandas as pd

DATA_PATH = Path(
    "data/raw/Supermart Grocery Sales - Retail Analytics Dataset.csv"
)

raw_df = pd.read_csv(DATA_PATH)

print("Total rows:", len(raw_df))

print("\n--- Original Order Date samples ---")
display(raw_df[["Order Date"]].head(15))

print("\n--- Original date data type ---")
print(raw_df["Order Date"].dtype)

print("\n--- Original date strings ---")
for value in raw_df["Order Date"].dropna().unique()[:15]:
    print(repr(value))

print("\n--- State values ---")
print(raw_df["State"].value_counts(dropna=False))

Total rows: 9994

--- Original Order Date samples ---

    Order Date
0   11-08-2017
1   11-08-2017
2   06-12-2017
3   10-11-2016
4   10-11-2016
5   06-09-2015
6   06-09-2015
7   06-09-2015
8   06-09-2015
9   06-09-2015
10  06-09-2015
11  06-09-2015
12   4/15/2018
13  12-05-2017
14  11/22/2016

--- Original date data type ---
object

--- Original date strings ---
'11-08-2017'
'06-12-2017'
'10-11-2016'
'06-09-2015'
'4/15/2018'
'12-05-2017'
'11/22/2016'
'11-11-2015'
'5/13/2015'
'8/27/2015'
'12-09-2017'
'7/16/2018'
'9/25/2016'
'1/16/2017'
'9/17/2016'

--- State values ---
State
Tamil Nadu    9994
Name: count, dtype: int64

In [26]:

# Parse each date format separately
dates = raw_df["Order Date"].astype("string").str.strip()

hyphen_mask = dates.str.contains("-", na=False)
slash_mask = dates.str.contains("/", na=False)

parsed_dates = pd.Series(
    pd.NaT, index=raw_df.index, dtype="datetime64[ns]"
)

# Format 1: DD-MM-YYYY, e.g. 11-08-2017
parsed_dates.loc[hyphen_mask] = pd.to_datetime(
    dates.loc[hyphen_mask],
    format="%d-%m-%Y",
    errors="coerce"
)

# Format 2: M/D/YYYY, e.g. 4/15/2018
parsed_dates.loc[slash_mask] = pd.to_datetime(
    dates.loc[slash_mask],
    format="mixed",
    errors="coerce"
)

print("Total rows:", len(raw_df))
print("Successfully parsed:", parsed_dates.notna().sum())
print("Invalid or unparsed:", parsed_dates.isna().sum())

print("\nDate range:")
print("Start:", parsed_dates.min())
print("End:", parsed_dates.max())

print("\nSample verification:")
display(pd.DataFrame({
    "original_date": raw_df["Order Date"],
    "parsed_date": parsed_dates
}).head(15))

Total rows: 9994
Successfully parsed: 9994
Invalid or unparsed: 0

Date range:
Start: 2015-01-02 00:00:00
End: 2018-12-30 00:00:00

Sample verification:

   original_date parsed_date
0     11-08-2017  2017-08-11
1     11-08-2017  2017-08-11
2     06-12-2017  2017-12-06
3     10-11-2016  2016-11-10
4     10-11-2016  2016-11-10
5     06-09-2015  2015-09-06
6     06-09-2015  2015-09-06
7     06-09-2015  2015-09-06
8     06-09-2015  2015-09-06
9     06-09-2015  2015-09-06
10    06-09-2015  2015-09-06
11    06-09-2015  2015-09-06
12     4/15/2018  2018-04-15
13    12-05-2017  2017-05-12
14    11/22/2016  2016-11-22

In [27]:
from pathlib import Path
import pandas as pd

clean_df = raw_df.copy()

In [28]:
clean_df.columns = clean_df.columns.str.strip()

In [29]:
clean_df["Order Date"] = parsed_dates

In [30]:
text_cols = clean_df.select_dtypes(
    include=["object", "string"]
).columns

for col in text_cols:
    clean_df[col] = clean_df[col].str.strip()

In [32]:
numeric_cols = ["Sales", "Discount", "Profit"]

for col in numeric_cols:
    clean_df[col] = pd.to_numeric(
        clean_df[col],
        errors="coerce"
    )

In [33]:
print("Original rows:", len(raw_df))
print("Cleaned rows:", len(clean_df))

Original rows: 9994
Cleaned rows: 9994

In [34]:
display(clean_df.isna().sum().to_frame("missing_count"))

               missing_count
Order ID                   0
Customer Name              0
Category                   0
Sub Category               0
City                       0
Order Date                 0
Region                     0
Sales                      0
Discount                   0
Profit                     0
State                      0

In [35]:
display(clean_df.dtypes.to_frame("data_type"))

                    data_type
Order ID               object
Customer Name          object
Category               object
Sub Category           object
City                   object
Order Date     datetime64[ns]
Region                 object
Sales                   int64
Discount              float64
Profit                float64
State                  object

In [36]:
display(clean_df["State"].value_counts(dropna=False))

State
Tamil Nadu    9994
Name: count, dtype: int64

In [37]:
print("Duplicate rows:", clean_df.duplicated().sum())

Duplicate rows: 0

In [38]:
assert len(clean_df) == len(raw_df), "Unexpected row count change!"

assert clean_df["Order Date"].notna().all(), "Invalid dates remain!"

assert clean_df["Sales"].notna().all(), "Invalid sales values!"

assert clean_df["Profit"].notna().all(), "Invalid profit values!"

print("\nAll validation assertions passed.")

All validation assertions passed.

In [39]:
from pathlib import Path

output_path = Path("data/processed")
output_path.mkdir(parents=True, exist_ok=True)

csv_path = output_path / "supermart_clean.csv"

clean_df.to_csv(
    csv_path,
    index=False,
    date_format="%Y-%m-%d"
)

print("Saved to:", csv_path)
print("Rows exported:", len(clean_df))
print("File size (KB):", round(csv_path.stat().st_size / 1024, 2))

Saved to: data/processed/supermart_clean.csv
Rows exported: 9994
File size (KB): 879.03

In [40]:
check_df = pd.read_csv(csv_path)

print("Rows:", len(check_df))
print("Columns:", check_df.columns.tolist())
display(check_df.head())

Rows: 9994
Columns: ['Order ID', 'Customer Name', 'Category', 'Sub Category', 'City', 'Order Date', 'Region', 'Sales', 'Discount', 'Profit', 'State']

,Order ID,Customer Name,Category,Sub Category,City,Order Date,Region,Sales,Discount,Profit,State
0,OD1,Harish,Oil & Masala,Masalas,Vellore,2017-08-11,North,1254,0.12,401.28,Tamil Nadu
1,OD2,Sudha,Beverages,Health Drinks,Krishnagiri,2017-08-11,South,749,0.18,149.80,Tamil Nadu
2,OD3,Hussain,Food Grains,Atta & Flour,Perambalur,2017-12-06,West,2360,0.21,165.20,Tamil Nadu
3,OD4,Jackson,Fruits & Veggies,Fresh Vegetables,Dharmapuri,2016-11-10,South,896,0.25,89.60,Tamil Nadu
4,OD5,Ridhesh,Food Grains,Organic Staples,Ooty,2016-11-10,South,2355,0.26,918.45,Tamil Nadu